# This is a basic pixi environment configuration for Python development
# For more options, see: https://pixi.sh/docs/reference/pixi.toml/

[project]
name = "PRESTOS"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.11,<3.13"
numpy = ">=1.24,<2.0"
scipy = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
scikit-learn = "*"
scikit-optimize = "*"
debugpy = ">=1.8.17,<2"
requests = ">=2.32.5,<3"
paramiko = ">=4.0.0,<5"

[pypi-dependencies]
pyqt6 = ">=6.9.1, <7"
#aurorafusion = { path = "../Aurora", editable = true }

#[feature.dev.dependencies]
# Add development dependencies here, e.g. pytest, black, etc.
