# This is a basic pixi environment configuration for Python development
# For more options, see: https://pixi.sh/docs/reference/pixi.toml/

[project]
name = "PRESTOS"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.8,<3.13"
numpy = "*"
scipy = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
scikit-learn = "*"
scikit-optimize = "*"
debugpy = ">=1.8.17,<2"
requests = ">=2.32.5,<3"

[pypi-dependencies]
pyqt6 = ">=6.9.1, <7"

# Platform-specific dependencies
#[target.linux-64.pypi-dependencies]
#aurorafusion = ">3.0.4"

#[target.osx-64.dependencies]
#aurorafusion = ">3.0.4"


#[feature.dev.dependencies]
# Add development dependencies here, e.g. pytest, black, etc.
